import{a as L,S as b,i as c}from"./assets/vendor-lDhL-8I6.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const w="49804709-aae3b3a79effefed9454c2d6d";async function v(t,e=1){return(await L("https://pixabay.com/api/",{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=new b(".gallery a",{captionsData:"alt",captionDelay:250});function S(t){const e=t.map(({webformatURL:s,largeImageURL:i,tags:o,likes:r,views:n,comments:g,downloads:h})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${s}" alt="${o}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${g}</p>
          <p><b>Downloads:</b> ${h}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",e),m.refresh()}function q(){p.innerHTML=""}function M(){f.classList.add("visible")}function P(){f.classList.remove("visible")}function $(){const t=document.querySelector(".load-more");t&&t.classList.add("is-visible")}function O(){const t=document.querySelector(".load-more");t&&t.classList.remove("is-visible")}function R(t){const e=document.querySelector("#breeds-list");e&&(e.innerHTML=t.map(s=>`<option value="${s}"></option>`).join(""))}const y=document.querySelector("#search-form"),l=y.elements.query,B=document.querySelector(".load-more");let a=1;const D=15;let d=0;y.addEventListener("submit",async t=>{t.preventDefault();const e=l.value.trim();if(!e){c.warning({message:"Search query is empty. Please try again.",position:"topRight",timeout:2e3});return}a=1,await u(e)});B.addEventListener("click",async()=>{a++,await u(l.value.trim())});async function u(t){M(),O();try{const e=await v(t,a),s=e.hits;if(a===1&&q(),s.length===0&&a===1){c.info({message:"No results found.",position:"topRight",timeout:2e3});return}S(s),m.refresh();const i=s.flatMap(r=>r.tags.split(",")).map(r=>r.trim().toLowerCase()),o=[...new Set(i)].slice(0,10);R(o),d=e.totalHits,d>D*a?$():a!==1&&c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:2e3}),T(t,a)}catch(e){c.error({message:`Error: ${e.message}`,position:"topRight",timeout:3e3})}finally{P()}}function T(t,e){const s=new URL(window.location);t&&s.searchParams.set("q",t),e>1?s.searchParams.set("p",e):s.searchParams.delete("p"),history.pushState({},"",s)}window.addEventListener("DOMContentLoaded",()=>{l.focus();const t=new URLSearchParams(window.location.search),e=t.get("q");a=parseInt(t.get("p"))||1,e&&(l.value=e,u(e))});
//# sourceMappingURL=index.js.map
